version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile.dev
    image: frontend
    volumes:
      - './src/frontend:/dnd_beyond_party/frontend'
      - './.eslintrc.js:/dnd_beyond_party/.eslintrc.js'
      - './babel.config.js:/dnd_beyond_party/babel.config.js'
      - './package-lock.json:/dnd_beyond_party/package.lock.json'
      - './package.json:/dnd_beyond_party/package.json'
      - './postcss.config.js:/dnd_beyond_party/postcss.config.js'
      - './webpack.config.js:/dnd_beyond_party/webpack.config.js'
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/', '||', 'exit', '1']
      interval: 10s
      timeout: 1m
      retries: 24
      start_period: 1m
  backend:
    build:
      context: .
      dockerfile: src/server/Dockerfile.dev
    image: backend
    volumes:
      - './src/server:/dnd_beyond_party/server'
      - './src/frontend/public:/dnd_beyond_party/server/public'
    ports:
      - '1337:1337'
    depends_on:
      - frontend
